In [4]:
import pandas as pd
import numpy as np  
import tensorflow as tf
from tensorflow import keras
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier

Data Cleaning

In [5]:
df = pd.read_csv('/Users/aajinkyaingalkar/Machine Learning_Project/Customer_Churn/data/WA_Fn-UseC_-Telco-Customer-Churn.xls')
df.head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No
7,6713-OKOMC,Female,0,No,No,10,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,No,Mailed check,29.75,301.9,No
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
9,6388-TABGU,Male,0,No,Yes,62,Yes,No,DSL,Yes,...,No,No,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,No

In [6]:
print(df.info(),df.shape)

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB
None (7043, 21)

In [7]:

df.drop(['customerID'], axis=1, inplace=True)

In [8]:
# df.info()
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df.isnull().sum()

gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [9]:
df[np.isnan(df['TotalCharges'])]

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,Male,0,No,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,Female,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [10]:
df[df['tenure'] == 0].index

Index([488, 753, 936, 1082, 1340, 3331, 3826, 4380, 5218, 6670, 6754], dtype='int64')

In [11]:
df.drop(labels=df[df['tenure'] == 0].index, axis=0, inplace=True)
df[df['tenure'] == 0].index

Index([], dtype='int64')

In [12]:
# Returns a DataFrame with only the rows where 'your_column' is NaN
df[df['TotalCharges'].isna() == True]

Empty DataFrame
Columns: [gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn]
Index: []

In [13]:
df.isnull().sum()
df.shape
df.fillna(df["TotalCharges"].mean())

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [14]:
df.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [15]:
df["SeniorCitizen"]= df["SeniorCitizen"].map({0: "No", 1: "Yes"})
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,No,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,No,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,No,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,No,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [16]:
df["Churn"][df["Churn"]=="No"].groupby(by=df["gender"]).count()

gender
Female    2544
Male      2619
Name: Churn, dtype: int64

In [17]:
df["Churn"][df["Churn"]=="Yes"].groupby(by=df["gender"]).count()

gender
Female    939
Male      930
Name: Churn, dtype: int64

In [18]:
df.info()

<class 'pandas.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7032 non-null   str
 1   SeniorCitizen     7032 non-null   str
 2   Partner           7032 non-null   str
 3   Dependents        7032 non-null   str
 4   tenure            7032 non-null   int64
 5   PhoneService      7032 non-null   str
 6   MultipleLines     7032 non-null   str
 7   InternetService   7032 non-null   str
 8   OnlineSecurity    7032 non-null   str
 9   OnlineBackup      7032 non-null   str
 10  DeviceProtection  7032 non-null   str
 11  TechSupport       7032 non-null   str
 12  StreamingTV       7032 non-null   str
 13  StreamingMovies   7032 non-null   str
 14  Contract          7032 non-null   str
 15  PaperlessBilling  7032 non-null   str
 16  PaymentMethod     7032 non-null   str
 17  MonthlyCharges    7032 non-null   float64
 18  TotalCharges      7032 non-null   float64
 19  Churn             7032 non-null   str
dtypes: float64(2), int64(1), str(17)
memory usage: 1.4 MB

In [19]:
df['gender'] = df['gender'].map({"Female" : 0, "Male" : 1})
df['SeniorCitizen'] = df['SeniorCitizen'].map({"No" : 0, "Yes" : 1})
df['Churn'] = df['Churn'].map({"No" : 0, "Yes" : 1})
df['Partner'] = df['Partner'].map({"No" : 0, "Yes" : 1})
df['Dependents'] = df['Dependents'].map({"No" : 0, "Yes" : 1})
df['PhoneService'] = df['PhoneService'].map({"No" : 0, "Yes" : 1})
df['PaperlessBilling'] = df['PaperlessBilling'].map({"No" : 0, "Yes" : 1})
df['MultipleLines'] = df['MultipleLines'].map({"No" : 0, "Yes" : 1, "No phone service" : 0})
df['OnlineBackup'] = df['OnlineBackup'].map({"No" : 0, "Yes" : 1, "No internet service" : 0})
df['OnlineSecurity'] = df['OnlineSecurity'].map({"No" : 0, "Yes" : 1, "No internet service" : 0})
df['DeviceProtection'] = df['DeviceProtection'].map({"No" : 0, "Yes" : 1, "No internet service" : 0})
df['TechSupport'] = df['TechSupport'].map({"No" : 0, "Yes" : 1, "No internet service" : 0})
df['StreamingTV'] = df['StreamingTV'].map({"No" : 0, "Yes" : 1, "No internet service" : 0})
df['StreamingMovies'] = df['StreamingMovies'].map({"No" : 0, "Yes" : 1, "No internet service" : 0})
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,0,DSL,0,1,0,0,0,0,Month-to-month,1,Electronic check,29.85,29.85,0
1,1,0,0,0,34,1,0,DSL,1,0,1,0,0,0,One year,0,Mailed check,56.95,1889.50,0
2,1,0,0,0,2,1,0,DSL,1,1,0,0,0,0,Month-to-month,1,Mailed check,53.85,108.15,1
3,1,0,0,0,45,0,0,DSL,1,0,1,1,0,0,One year,0,Bank transfer (automatic),42.30,1840.75,0
4,0,0,0,0,2,1,0,Fiber optic,0,0,0,0,0,0,Month-to-month,1,Electronic check,70.70,151.65,1

In [20]:
df.info()

<class 'pandas.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7032 non-null   int64
 1   SeniorCitizen     7032 non-null   int64
 2   Partner           7032 non-null   int64
 3   Dependents        7032 non-null   int64
 4   tenure            7032 non-null   int64
 5   PhoneService      7032 non-null   int64
 6   MultipleLines     7032 non-null   int64
 7   InternetService   7032 non-null   str
 8   OnlineSecurity    7032 non-null   int64
 9   OnlineBackup      7032 non-null   int64
 10  DeviceProtection  7032 non-null   int64
 11  TechSupport       7032 non-null   int64
 12  StreamingTV       7032 non-null   int64
 13  StreamingMovies   7032 non-null   int64
 14  Contract          7032 non-null   str
 15  PaperlessBilling  7032 non-null   int64
 16  PaymentMethod     7032 non-null   str
 17  MonthlyCharges    7032 non-null   float64
 18  TotalCharges      7032 non-null   float64
 19  Churn             7032 non-null   int64
dtypes: float64(2), int64(15), str(3)
memory usage: 1.4 MB

In [21]:
df = pd.get_dummies(df, columns=['Contract', 'PaymentMethod', 'InternetService'], drop_first=True)
df['StreamingMovies'].value_counts()

StreamingMovies
0    4301
1    2731
Name: count, dtype: int64

In [22]:
df.info()

<class 'pandas.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 24 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   gender                                 7032 non-null   int64
 1   SeniorCitizen                          7032 non-null   int64
 2   Partner                                7032 non-null   int64
 3   Dependents                             7032 non-null   int64
 4   tenure                                 7032 non-null   int64
 5   PhoneService                           7032 non-null   int64
 6   MultipleLines                          7032 non-null   int64
 7   OnlineSecurity                         7032 non-null   int64
 8   OnlineBackup                           7032 non-null   int64
 9   DeviceProtection                       7032 non-null   int64
 10  TechSupport                            7032 non-null   int64
 11  StreamingTV                            7032 non-null   int64
 12  StreamingMovies                        7032 non-null   int64
 13  PaperlessBilling                       7032 non-null   int64
 14  MonthlyCharges                         7032 non-null   float64
 15  TotalCharges                           7032 non-null   float64
 16  Churn                                  7032 non-null   int64
 17  Contract_One year                      7032 non-null   bool
 18  Contract_Two year                      7032 non-null   bool
 19  PaymentMethod_Credit card (automatic)  7032 non-null   bool
 20  PaymentMethod_Electronic check         7032 non-null   bool
 21  PaymentMethod_Mailed check             7032 non-null   bool
 22  InternetService_Fiber optic            7032 non-null   bool
 23  InternetService_No                     7032 non-null   bool
dtypes: bool(7), float64(2), int64(15)
memory usage: 1.3 MB

In [23]:
def object_to_int(dataframe_series):
    if dataframe_series.dtype=='object':
        dataframe_series = LabelEncoder().fit_transform(dataframe_series)
    return dataframe_series

In [24]:
df = df.apply(lambda x: object_to_int(x))
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,MonthlyCharges,TotalCharges,Churn,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,InternetService_Fiber optic,InternetService_No
0,0,0,1,0,1,0,0,0,1,0,...,29.85,29.85,0,False,False,False,True,False,False,False
1,1,0,0,0,34,1,0,1,0,1,...,56.95,1889.50,0,True,False,False,False,True,False,False
2,1,0,0,0,2,1,0,1,1,0,...,53.85,108.15,1,False,False,False,False,True,False,False
3,1,0,0,0,45,0,0,1,0,1,...,42.30,1840.75,0,True,False,False,False,False,False,False
4,0,0,0,0,2,1,0,0,0,0,...,70.70,151.65,1,False,False,False,True,False,True,False

In [25]:
df.info()

<class 'pandas.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 24 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   gender                                 7032 non-null   int64
 1   SeniorCitizen                          7032 non-null   int64
 2   Partner                                7032 non-null   int64
 3   Dependents                             7032 non-null   int64
 4   tenure                                 7032 non-null   int64
 5   PhoneService                           7032 non-null   int64
 6   MultipleLines                          7032 non-null   int64
 7   OnlineSecurity                         7032 non-null   int64
 8   OnlineBackup                           7032 non-null   int64
 9   DeviceProtection                       7032 non-null   int64
 10  TechSupport                            7032 non-null   int64
 11  StreamingTV                            7032 non-null   int64
 12  StreamingMovies                        7032 non-null   int64
 13  PaperlessBilling                       7032 non-null   int64
 14  MonthlyCharges                         7032 non-null   float64
 15  TotalCharges                           7032 non-null   float64
 16  Churn                                  7032 non-null   int64
 17  Contract_One year                      7032 non-null   bool
 18  Contract_Two year                      7032 non-null   bool
 19  PaymentMethod_Credit card (automatic)  7032 non-null   bool
 20  PaymentMethod_Electronic check         7032 non-null   bool
 21  PaymentMethod_Mailed check             7032 non-null   bool
 22  InternetService_Fiber optic            7032 non-null   bool
 23  InternetService_No                     7032 non-null   bool
dtypes: bool(7), float64(2), int64(15)
memory usage: 1.3 MB

In [26]:
boolean_columns = df.select_dtypes(include='bool').columns
boolean_columns
df[boolean_columns] = df[boolean_columns].astype(int)
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,MonthlyCharges,TotalCharges,Churn,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,InternetService_Fiber optic,InternetService_No
0,0,0,1,0,1,0,0,0,1,0,...,29.85,29.85,0,0,0,0,1,0,0,0
1,1,0,0,0,34,1,0,1,0,1,...,56.95,1889.50,0,1,0,0,0,1,0,0
2,1,0,0,0,2,1,0,1,1,0,...,53.85,108.15,1,0,0,0,0,1,0,0
3,1,0,0,0,45,0,0,1,0,1,...,42.30,1840.75,0,1,0,0,0,0,0,0
4,0,0,0,0,2,1,0,0,0,0,...,70.70,151.65,1,0,0,0,1,0,1,0

In [27]:
df.info()

<class 'pandas.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 24 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   gender                                 7032 non-null   int64
 1   SeniorCitizen                          7032 non-null   int64
 2   Partner                                7032 non-null   int64
 3   Dependents                             7032 non-null   int64
 4   tenure                                 7032 non-null   int64
 5   PhoneService                           7032 non-null   int64
 6   MultipleLines                          7032 non-null   int64
 7   OnlineSecurity                         7032 non-null   int64
 8   OnlineBackup                           7032 non-null   int64
 9   DeviceProtection                       7032 non-null   int64
 10  TechSupport                            7032 non-null   int64
 11  StreamingTV                            7032 non-null   int64
 12  StreamingMovies                        7032 non-null   int64
 13  PaperlessBilling                       7032 non-null   int64
 14  MonthlyCharges                         7032 non-null   float64
 15  TotalCharges                           7032 non-null   float64
 16  Churn                                  7032 non-null   int64
 17  Contract_One year                      7032 non-null   int64
 18  Contract_Two year                      7032 non-null   int64
 19  PaymentMethod_Credit card (automatic)  7032 non-null   int64
 20  PaymentMethod_Electronic check         7032 non-null   int64
 21  PaymentMethod_Mailed check             7032 non-null   int64
 22  InternetService_Fiber optic            7032 non-null   int64
 23  InternetService_No                     7032 non-null   int64
dtypes: float64(2), int64(22)
memory usage: 1.6 MB

In [28]:
df.shape

(7032, 24)

Data Imbalance

In [29]:
df['Churn'].value_counts()
# Clearly shows that the dataset is imbalanced.
#  The number of customers who have not churned is significantly higher than those who have churned. 
# This imbalance can affect the performance of machine learning models, as they may become biased towards the majority class.
#  To address this issue, techniques such as oversampling the minority class, undersampling the majority class, or using algorithms that are robust to class imbalance can be employed.

Churn
0    5163
1    1869
Name: count, dtype: int64

SMOTE (Synthetic Minority Over-sampling Technique)

How SMOTE Works
Instead of simply duplicating existing data points (which leads to overfitting), SMOTE synthesizes brand new points:
1. It looks at a minority class sample.
2. It finds its k-nearest neighbors (typically k=5) belonging to the same class.
3. It draws a line between the sample and a randomly selected neighbor.
4. It places a new synthetic data point somewhere along that line via interpolation.

In [30]:
X = df.drop(columns = ['Churn'])
y = df['Churn'].values

In [31]:
#train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((5625, 23), (1407, 23), (5625,), (1407,))

In [32]:
smote = SMOTE(random_state=42)
resampled = smote.fit_resample(X_train, y_train)
X_train_resampled = resampled[0]
y_train_resampled = resampled[1]
resampled_test = smote.fit_resample(X_test, y_test)
X_test_resampled = resampled_test[0]
y_test_resampled = resampled_test[1]
X_test_resampled.shape, y_test_resampled.shape

((2066, 23), (2066,))

In [33]:
print(pd.Series(y_train).value_counts())
print(pd.Series(y_train_resampled).value_counts())
X_train_resampled.shape[1]

0    4130
1    1495
Name: count, dtype: int64
1    4130
0    4130
Name: count, dtype: int64

23

 ========== ANN Used For Below With Accuray ======

In [34]:
#
model = tf.keras.Sequential([
    keras.layers.Dense(64, input_shape=(X_train_resampled.shape[1],), activation='relu'),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train_resampled, y_train_resampled, epochs=100)

/Users/aajinkyaingalkar/Machine Learning_Project/Customer_Churn/.venv/lib/python3.14/site-packages/keras/src/layers/core/dense.py:102: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.6461 - loss: 2.3214
Epoch 2/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.7076 - loss: 1.5785
Epoch 3/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 5s 18ms/step - accuracy: 0.7205 - loss: 1.4087
Epoch 4/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7303 - loss: 1.2491
Epoch 5/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7402 - loss: 1.1563
Epoch 6/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7482 - loss: 1.1730
Epoch 7/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7300 - loss: 1.3444
Epoch 8/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7660 - loss: 0.8489
Epoch 9/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7680 - loss: 0.8437
Epoch 10/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7604 - loss: 0.9863
Epoch 11/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7626 - loss: 0.9457
Epoch 12/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7683 - loss: 0.8395
Epoch 13/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7701 - loss: 0.8250
Epoch 14/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7633 - loss: 0.9524
Epoch 15/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7748 - loss: 0.8123
Epoch 16/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7740 - loss: 0.7559
Epoch 17/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7671 - loss: 0.8772
Epoch 18/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7699 - loss: 0.8331
Epoch 19/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7715 - loss: 0.8131
Epoch 20/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7762 - loss: 0.7751
Epoch 21/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7734 - loss: 0.7714
Epoch 22/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7754 - loss: 0.7557
Epoch 23/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7782 - loss: 0.7484
Epoch 24/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7822 - loss: 0.6928
Epoch 25/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7811 - loss: 0.7023
Epoch 26/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7840 - loss: 0.6816
Epoch 27/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7850 - loss: 0.6744
Epoch 28/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7879 - loss: 0.6599
Epoch 29/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7861 - loss: 0.6569
Epoch 30/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7903 - loss: 0.6404
Epoch 31/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7892 - loss: 0.6352
Epoch 32/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7914 - loss: 0.6235
Epoch 33/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7910 - loss: 0.6182
Epoch 34/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7861 - loss: 0.6386
Epoch 35/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7906 - loss: 0.6068
Epoch 36/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7913 - loss: 0.5976
Epoch 37/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7909 - loss: 0.5809
Epoch 38/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7870 - loss: 0.5834
Epoch 39/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7913 - loss: 0.5681
Epoch 40/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7937 - loss: 0.5621
Epoch 41/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7935 - loss: 0.5544
Epoch 42/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7947 - loss: 0.5517
Epoch 43/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7959 - loss: 0.5451
Epoch 44/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7964 - loss: 0.5400
Epoch 45/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7966 - loss: 0.5346
Epoch 46/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7959 - loss: 0.5325
Epoch 47/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7953 - loss: 0.5273
Epoch 48/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7961 - loss: 0.5196
Epoch 49/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7967 - loss: 0.5154
Epoch 50/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8001 - loss: 0.5066
Epoch 51/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7995 - loss: 0.5025
Epoch 52/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7999 - loss: 0.4999
Epoch 53/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8017 - loss: 0.4975
Epoch 54/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8029 - loss: 0.4919
Epoch 55/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8041 - loss: 0.4948
Epoch 56/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.8041 - loss: 0.4943
Epoch 57/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8047 - loss: 0.4877
Epoch 58/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8034 - loss: 0.4787
Epoch 59/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8054 - loss: 0.4728
Epoch 60/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8077 - loss: 0.4680
Epoch 61/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8075 - loss: 0.4637
Epoch 62/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8086 - loss: 0.4572
Epoch 63/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8077 - loss: 0.4624
Epoch 64/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4534
Epoch 65/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8092 - loss: 0.4484
Epoch 66/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8086 - loss: 0.4444
Epoch 67/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8113 - loss: 0.4437
Epoch 68/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8103 - loss: 0.4372
Epoch 69/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8057 - loss: 0.4393
Epoch 70/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8082 - loss: 0.4375
Epoch 71/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.8084 - loss: 0.4285
Epoch 72/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8094 - loss: 0.4357
Epoch 73/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8120 - loss: 0.4354
Epoch 74/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8132 - loss: 0.4195
Epoch 75/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8148 - loss: 0.4197
Epoch 76/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8151 - loss: 0.4212
Epoch 77/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8163 - loss: 0.4217
Epoch 78/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8174 - loss: 0.4203
Epoch 79/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8155 - loss: 0.4218
Epoch 80/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8195 - loss: 0.4155
Epoch 81/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8196 - loss: 0.4148
Epoch 82/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8195 - loss: 0.4162
Epoch 83/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8176 - loss: 0.4178
Epoch 84/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8189 - loss: 0.4136
Epoch 85/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8188 - loss: 0.4131
Epoch 86/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8190 - loss: 0.4138
Epoch 87/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8201 - loss: 0.4152
Epoch 88/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8127 - loss: 0.4239
Epoch 89/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8151 - loss: 0.4182
Epoch 90/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8190 - loss: 0.4132
Epoch 91/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8182 - loss: 0.4091
Epoch 92/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8201 - loss: 0.4084
Epoch 93/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8206 - loss: 0.4047
Epoch 94/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8212 - loss: 0.4004
Epoch 95/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8225 - loss: 0.4001
Epoch 96/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8232 - loss: 0.3973
Epoch 97/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8231 - loss: 0.3961
Epoch 98/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8234 - loss: 0.3961
Epoch 99/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8232 - loss: 0.3934
Epoch 100/100
259/259 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8234 - loss: 0.3913

In [35]:
predictions = model.predict(X_test_resampled)
predictions_labels = np.argmax(predictions, axis=1)
print(predictions_labels[1010])
print(y_test_resampled[1010])
def get_accuracy(y_true, y_pred):
    accuracy = np.sum(y_true == y_pred) / len(y_true)
    return accuracy

accuracy = get_accuracy(y_test_resampled, predictions_labels)
print(f'Accuracy: {accuracy*100}%')
print(classification_report(y_test_resampled, predictions_labels))

65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
0
1
Accuracy: 50.0%
              precision    recall  f1-score   support

           0       0.50      1.00      0.67      1033
           1       0.00      0.00      0.00      1033

    accuracy                           0.50      2066
   macro avg       0.25      0.50      0.33      2066
weighted avg       0.25      0.50      0.33      2066

/Users/aajinkyaingalkar/Machine Learning_Project/Customer_Churn/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/aajinkyaingalkar/Machine Learning_Project/Customer_Churn/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/aajinkyaingalkar/Machine Learning_Project/Customer_Churn/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

The Accuracy For ANN Is Not The Best

========================= Gotta Try It With Some Other Models =========================

In [37]:
# X_fit, X_val, y_fit, y_val = train_test_split(
#     X_train, y_train, test_size=0.2, stratify=y_train, random_state=42
# )

# # Weight churners during training; don't also apply SMOTE here.
# negatives = (y_fit == 0).sum()
# positives = (y_fit == 1).sum()

# model = XGBClassifier(
#     eval_metric="logloss",
#     scale_pos_weight=negatives / positives,
#     random_state=42
# )
# model.fit(X_fit, y_fit)

# # Select a threshold using validation data
# val_scores = model.predict_proba(X_val)[:, 1]
# thresholds = np.arange(0.05, 0.96, 0.01)

# best_threshold = max(
#     thresholds,
#     key=lambda t: f1_score(y_val, (val_scores >= t).astype(int))
# )
# print("Best validation threshold for F1:", best_threshold)

# # Evaluate on the untouched test set
# test_scores = model.predict_proba(X_test)[:, 1]
# test_predictions = (test_scores >= best_threshold).astype(int)
# print(classification_report(y_test, test_predictions))

In [38]:
xgb_model = XGBClassifier()
xgb_model.fit(X_train_resampled, y_train_resampled)
xgb_predictions = xgb_model.predict(X_test_resampled)
# probabilities = xgb_model.predict_proba(X_test_resampled)[:, 1]  # Get probabilities for the positive class
# y_pred = (probabilities >= 0.25).astype(int)  # Convert probabilities to binary predictions
xgb_accuracy = get_accuracy(y_test_resampled, xgb_predictions)
print(f'XGBoost Accuracy: {xgb_accuracy*100:.2f}%')
print(classification_report(y_test_resampled, xgb_predictions))

XGBoost Accuracy: 81.32%
              precision    recall  f1-score   support

           0       0.81      0.82      0.81      1033
           1       0.82      0.81      0.81      1033

    accuracy                           0.81      2066
   macro avg       0.81      0.81      0.81      2066
weighted avg       0.81      0.81      0.81      2066

In [39]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, roc_auc_score
# churn_scores = xgb_model.predict_proba(X_test)[:, 1]
# print(f"ROC-AUC Score: {roc_auc_score(y_test, churn_scores):.2f}")
# print("Different Thresholds:")
# for threshold in [0.0009, 0.05, 0.55, 0.75, 0.9]:
#     y_pred = (churn_scores >= threshold).astype(int)
#     print(f"Threshold: {threshold}")
#     print(f"Recall: {recall_score(y_test, y_pred)*100:.2f}%")
#     print(f"Precision: {precision_score(y_test, y_pred)*100:.2f}%")
#     print(f"F1-Score: {f1_score(y_test, y_pred)*100:.2f}%")
#     print(f"ROC-AUC: {roc_auc_score(y_test, churn_scores)*100:.2f}%")
#     print(f'accuracy: {get_accuracy(y_test, y_pred)*100:.2f}%')
#     print("-" * 30)
churn_scores = xgb_model.predict_proba(X_test)[:, 1]

print(f"ROC-AUC: {roc_auc_score(y_test, churn_scores):.3f}")

for threshold in [0.0009, 0.05, 0.55, 0.75, 0.9]:
    y_pred = (churn_scores >= threshold).astype(int)

    print(f"\nThreshold: {threshold}")
    print(f"Recall:    {recall_score(y_test, y_pred, zero_division=0):.2%}")
    print(f"Precision: {precision_score(y_test, y_pred, zero_division=0):.2%}")
    print(f"F1-score:  {f1_score(y_test, y_pred, zero_division=0):.2%}")
    print(f"Accuracy:  {accuracy_score(y_test, y_pred):.2%}")

ROC-AUC: 0.799

Threshold: 0.0009
Recall:    99.73%
Precision: 27.75%
F1-score:  43.42%
Accuracy:  30.92%

Threshold: 0.05
Recall:    90.11%
Precision: 38.91%
F1-score:  54.35%
Accuracy:  59.77%

Threshold: 0.55
Recall:    53.21%
Precision: 53.93%
F1-score:  53.57%
Accuracy:  75.48%

Threshold: 0.75
Recall:    37.43%
Precision: 64.81%
F1-score:  47.46%
Accuracy:  77.97%

Threshold: 0.9
Recall:    17.91%
Precision: 74.44%
F1-score:  28.88%
Accuracy:  76.55%

In [40]:
random_forest_model = RandomForestClassifier()
random_forest_model.fit(X_train_resampled, y_train_resampled)
rf_predictions = random_forest_model.predict(X_test_resampled)  
rf_accuracy = get_accuracy(y_test_resampled, rf_predictions)
print(f'Random Forest Accuracy: {rf_accuracy*100:.2f}%')

Random Forest Accuracy: 79.72%

==== We Saw That XGBoost Was Much Better In Initial Recall Therefore We Will Tune It With Optuna ====

In [42]:
import optuna
THRESHOLD = 0.3
def objective(trial):
    # Define the hyperparameter search space
    parameters = {
        "n_estimators": trial.suggest_int('n_estimators', 50, 300),
        "learning_rate": trial.suggest_float('learning_rate', 0.01, 0.3),
        "max_depth": trial.suggest_int('max_depth', 3, 20),
        "subsample": trial.suggest_float('subsample', 0.5, 1.0),
        "gamma": trial.suggest_float('gamma', 0.0, 5.0),
        "reg_alpha": trial.suggest_float('reg_alpha', 0.0, 5.0),
        "reg_lambda": trial.suggest_float('reg_lambda', 0.0, 5.0),
    }
    # Create and train the Random Forest model with the suggested hyperparameters
    model = XGBClassifier(**parameters)
    model.fit(X_train_resampled, y_train_resampled)
    proba = model.predict_proba(X_test_resampled)[:, 1]
    y_pred = (proba >= THRESHOLD).astype(int)
    return recall_score(y_test_resampled, y_pred)

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=50)
print("Best hyperparameters:", study.best_params)
print("Best recall score:", study.best_value)

[I 2026-10-07 22:17:23,230] A new study created in memory with name: no-name-4b3da26a-7e08-448f-9129-e2d1e9f93985
[I 2026-10-07 22:17:24,419] Trial 0 finished with value: 0.9051306873184899 and parameters: {'n_estimators': 165, 'learning_rate': 0.06859574314662739, 'max_depth': 13, 'subsample': 0.6387148753986096, 'gamma': 3.9338284154118774, 'reg_alpha': 1.8737417911577974, 'reg_lambda': 3.8967947882219094}. Best is trial 0 with value: 0.9051306873184899.
[I 2026-10-07 22:17:25,095] Trial 1 finished with value: 0.9070667957405615 and parameters: {'n_estimators': 203, 'learning_rate': 0.17180082352948461, 'max_depth': 6, 'subsample': 0.5395018944114731, 'gamma': 1.4042448217079646, 'reg_alpha': 2.952106387192774, 'reg_lambda': 3.471445575047305}. Best is trial 1 with value: 0.9070667957405615.
[I 2026-10-07 22:17:25,508] Trial 2 finished with value: 0.914811229428848 and parameters: {'n_estimators': 76, 'learning_rate': 0.11205405274156213, 'max_depth': 11, 'subsample': 0.7341823508281051, 'gamma': 3.8639914632101564, 'reg_alpha': 2.3360623653323556, 'reg_lambda': 2.0220639041768984}. Best is trial 2 with value: 0.914811229428848.
[I 2026-10-07 22:17:26,575] Trial 3 finished with value: 0.8799612778315585 and parameters: {'n_estimators': 278, 'learning_rate': 0.23282734997168775, 'max_depth': 6, 'subsample': 0.5431558897647786, 'gamma': 0.734206146187566, 'reg_alpha': 2.2219753245874974, 'reg_lambda': 0.4638925375814712}. Best is trial 2 with value: 0.914811229428848.
[I 2026-10-07 22:17:26,793] Trial 4 finished with value: 0.9322362052274927 and parameters: {'n_estimators': 183, 'learning_rate': 0.18907879863865495, 'max_depth': 3, 'subsample': 0.9178370401779234, 'gamma': 4.823674441199062, 'reg_alpha': 2.742256287094227, 'reg_lambda': 4.454351872509033}. Best is trial 4 with value: 0.9322362052274927.
[I 2026-10-07 22:17:27,784] Trial 5 finished with value: 0.904162633107454 and parameters: {'n_estimators': 250, 'learning_rate': 0.026344513792183145, 'max_depth': 8, 'subsample': 0.9782947586525006, 'gamma': 2.3047495261452386, 'reg_alpha': 4.067569135880344, 'reg_lambda': 0.6024887928582034}. Best is trial 4 with value: 0.9322362052274927.
[I 2026-10-07 22:17:28,171] Trial 6 finished with value: 0.8954501452081317 and parameters: {'n_estimators': 52, 'learning_rate': 0.10834165272275388, 'max_depth': 18, 'subsample': 0.6603348093506379, 'gamma': 1.5301269697169784, 'reg_alpha': 0.683998511248553, 'reg_lambda': 0.2442727559020358}. Best is trial 4 with value: 0.9322362052274927.
[I 2026-10-07 22:17:28,540] Trial 7 finished with value: 0.9070667957405615 and parameters: {'n_estimators': 267, 'learning_rate': 0.20122545854382778, 'max_depth': 12, 'subsample': 0.866882634599941, 'gamma': 4.678892014828111, 'reg_alpha': 3.1449618360503044, 'reg_lambda': 3.622244087367925}. Best is trial 4 with value: 0.9322362052274927.
[I 2026-10-07 22:17:28,942] Trial 8 finished with value: 0.920619554695063 and parameters: {'n_estimators': 251, 'learning_rate': 0.13780120668840223, 'max_depth': 6, 'subsample': 0.7081237690158927, 'gamma': 3.6520550926354147, 'reg_alpha': 4.066617407622507, 'reg_lambda': 0.07950574991516801}. Best is trial 4 with value: 0.9322362052274927.
[I 2026-10-07 22:17:29,126] Trial 9 finished with value: 0.9167473378509197 and parameters: {'n_estimators': 108, 'learning_rate': 0.20829043508995493, 'max_depth': 5, 'subsample': 0.9481313706325907, 'gamma': 3.3591553640539895, 'reg_alpha': 4.094588928820583, 'reg_lambda': 0.18868112376677237}. Best is trial 4 with value: 0.9322362052274927.
[I 2026-10-07 22:17:29,457] Trial 10 finished with value: 0.9128751210067764 and parameters: {'n_estimators': 192, 'learning_rate': 0.17345674058464444, 'max_depth': 6, 'subsample': 0.9675023082110321, 'gamma': 4.53385696183922, 'reg_alpha': 0.9176348900725255, 'reg_lambda': 3.5381255540472916}. Best is trial 4 with value: 0.9322362052274927.
[I 2026-10-07 22:17:30,018] Trial 11 finished with value: 0.9293320425943853 and parameters: {'n_estimators': 282, 'learning_rate': 0.0824116564499058, 'max_depth': 4, 'subsample': 0.7109354978705559, 'gamma': 3.848905086584522, 'reg_alpha': 4.5531897066703015, 'reg_lambda': 1.6330949000103745}. Best is trial 4 with value: 0.9322362052274927.
[I 2026-10-07 22:17:30,496] Trial 12 finished with value: 0.9138431752178122 and parameters: {'n_estimators': 239, 'learning_rate': 0.0930672095889865, 'max_depth': 6, 'subsample': 0.7467568011063428, 'gamma': 3.4726084630738776, 'reg_alpha': 4.9387044293274185, 'reg_lambda': 1.9676218415820368}. Best is trial 4 with value: 0.9322362052274927.
[I 2026-10-07 22:17:30,798] Trial 13 finished with value: 0.9167473378509197 and parameters: {'n_estimators': 234, 'learning_rate': 0.217398718126271, 'max_depth': 7, 'subsample': 0.7980532761956549, 'gamma': 4.47833060620068, 'reg_alpha': 3.081906498957813, 'reg_lambda': 1.9981722411520741}. Best is trial 4 with value: 0.9322362052274927.
[I 2026-10-07 22:17:31,086] Trial 14 finished with value: 0.9264278799612778 and parameters: {'n_estimators': 176, 'learning_rate': 0.12852249997353715, 'max_depth': 4, 'subsample': 0.5692434995602993, 'gamma': 4.213643259715067, 'reg_alpha': 4.852854655381605, 'reg_lambda': 2.2846665784172853}. Best is trial 4 with value: 0.9322362052274927.
[I 2026-10-07 22:17:31,368] Trial 15 finished with value: 0.9215876089060987 and parameters: {'n_estimators': 208, 'learning_rate': 0.19729718676957586, 'max_depth': 4, 'subsample': 0.8327216257162225, 'gamma': 3.900550261343916, 'reg_alpha': 4.143869001818005, 'reg_lambda': 3.2980184628002465}. Best is trial 4 with value: 0.9322362052274927.
[I 2026-10-07 22:17:31,876] Trial 16 finished with value: 0.9215876089060987 and parameters: {'n_estimators': 235, 'learning_rate': 0.04754207943174213, 'max_depth': 5, 'subsample': 0.6593750901551341, 'gamma': 4.137673955323679, 'reg_alpha': 3.259667887350238, 'reg_lambda': 2.308747056592499}. Best is trial 4 with value: 0.9322362052274927.
[I 2026-10-07 22:17:32,286] Trial 17 finished with value: 0.9225556631171346 and parameters: {'n_estimators': 294, 'learning_rate': 0.057842824146981664, 'max_depth': 5, 'subsample': 0.8266067435588216, 'gamma': 4.892281679674185, 'reg_alpha': 2.6849142804064043, 'reg_lambda': 3.3738354958463956}. Best is trial 4 with value: 0.9322362052274927.
[I 2026-10-07 22:17:32,570] Trial 18 finished with value: 0.9157792836398838 and parameters: {'n_estimators': 293, 'learning_rate': 0.1870241974593142, 'max_depth': 6, 'subsample': 0.8846617726826905, 'gamma': 4.801792003861217, 'reg_alpha': 3.79741462339853, 'reg_lambda': 2.9071263441158863}. Best is trial 4 with value: 0.9322362052274927.
[I 2026-10-07 22:17:32,703] Trial 19 finished with value: 0.9312681510164569 and parameters: {'n_estimators': 95, 'learning_rate': 0.20333070147571922, 'max_depth': 3, 'subsample': 0.8224545967365535, 'gamma': 4.956828751864143, 'reg_alpha': 3.082955121748025, 'reg_lambda': 4.840555698316266}. Best is trial 4 with value: 0.9322362052274927.
[I 2026-10-07 22:17:32,872] Trial 20 finished with value: 0.9138431752178122 and parameters: {'n_estimators': 126, 'learning_rate': 0.19171730328281314, 'max_depth': 6, 'subsample': 0.9515650012748404, 'gamma': 4.1058903328703975, 'reg_alpha': 4.325122610123571, 'reg_lambda': 4.765889784554548}. Best is trial 4 with value: 0.9322362052274927.
[I 2026-10-07 22:17:33,032] Trial 21 finished with value: 0.9332042594385286 and parameters: {'n_estimators': 125, 'learning_rate': 0.23629408082612496, 'max_depth': 3, 'subsample': 0.8553160136913495, 'gamma': 4.980981417723924, 'reg_alpha': 2.2092265717886868, 'reg_lambda': 4.200252070661157}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:33,134] Trial 22 finished with value: 0.9283639883833494 and parameters: {'n_estimators': 65, 'learning_rate': 0.2401387828460141, 'max_depth': 4, 'subsample': 0.9501294908307569, 'gamma': 4.966439714482011, 'reg_alpha': 2.946182315193857, 'reg_lambda': 4.2411490419488835}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:33,274] Trial 23 finished with value: 0.9235237173281704 and parameters: {'n_estimators': 109, 'learning_rate': 0.2646817024608928, 'max_depth': 5, 'subsample': 0.7910344367441766, 'gamma': 4.974842989084536, 'reg_alpha': 2.4765601691516, 'reg_lambda': 4.103172872731598}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:33,426] Trial 24 finished with value: 0.9225556631171346 and parameters: {'n_estimators': 112, 'learning_rate': 0.2006681383200792, 'max_depth': 4, 'subsample': 0.8841754210859473, 'gamma': 4.181290310281892, 'reg_alpha': 1.8571911978157838, 'reg_lambda': 4.447883758006843}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:33,667] Trial 25 finished with value: 0.9196515004840271 and parameters: {'n_estimators': 98, 'learning_rate': 0.14731893437144059, 'max_depth': 4, 'subsample': 0.8714569086319021, 'gamma': 4.503868003111935, 'reg_alpha': 3.4535396477244444, 'reg_lambda': 4.975203020103467}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:33,838] Trial 26 finished with value: 0.920619554695063 and parameters: {'n_estimators': 137, 'learning_rate': 0.2544610797025968, 'max_depth': 4, 'subsample': 0.9554757879049969, 'gamma': 4.520221413302948, 'reg_alpha': 2.8018617117659375, 'reg_lambda': 3.713875164407192}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:34,018] Trial 27 finished with value: 0.9186834462729913 and parameters: {'n_estimators': 128, 'learning_rate': 0.2710550418031913, 'max_depth': 5, 'subsample': 0.8535796776668743, 'gamma': 3.6239703323761563, 'reg_alpha': 2.186780934667556, 'reg_lambda': 4.372797823433589}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:34,208] Trial 28 finished with value: 0.9293320425943853 and parameters: {'n_estimators': 175, 'learning_rate': 0.19025636114993844, 'max_depth': 3, 'subsample': 0.8867093305404827, 'gamma': 4.623701172633624, 'reg_alpha': 2.810149374690558, 'reg_lambda': 3.749134689305417}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:34,384] Trial 29 finished with value: 0.9264278799612778 and parameters: {'n_estimators': 141, 'learning_rate': 0.19942331929383755, 'max_depth': 3, 'subsample': 0.7874712552301727, 'gamma': 4.143077387970607, 'reg_alpha': 2.4553165608444645, 'reg_lambda': 4.800807812883454}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:34,522] Trial 30 finished with value: 0.9244917715392061 and parameters: {'n_estimators': 92, 'learning_rate': 0.20469094879948907, 'max_depth': 3, 'subsample': 0.7389519040772097, 'gamma': 4.4859105242511985, 'reg_alpha': 2.124315552048784, 'reg_lambda': 3.8809025664779604}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:34,646] Trial 31 finished with value: 0.9186834462729913 and parameters: {'n_estimators': 60, 'learning_rate': 0.24916796091263518, 'max_depth': 4, 'subsample': 0.8336652406650079, 'gamma': 4.772669663721298, 'reg_alpha': 2.8852593382741087, 'reg_lambda': 4.506879755128468}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:34,768] Trial 32 finished with value: 0.9186834462729913 and parameters: {'n_estimators': 50, 'learning_rate': 0.16066871887211132, 'max_depth': 5, 'subsample': 0.8398490784093456, 'gamma': 4.6030805666711485, 'reg_alpha': 2.60077225636443, 'reg_lambda': 4.033099530651246}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:34,978] Trial 33 finished with value: 0.920619554695063 and parameters: {'n_estimators': 218, 'learning_rate': 0.2881628400158561, 'max_depth': 5, 'subsample': 0.8644301739868523, 'gamma': 4.901003860078273, 'reg_alpha': 2.8359855834319925, 'reg_lambda': 4.271286859625081}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:35,234] Trial 34 finished with value: 0.9167473378509197 and parameters: {'n_estimators': 143, 'learning_rate': 0.13712193741782217, 'max_depth': 4, 'subsample': 0.9369477637201645, 'gamma': 4.1685326650711225, 'reg_alpha': 3.1179258954764757, 'reg_lambda': 4.631994450514627}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:35,396] Trial 35 finished with value: 0.9273959341723137 and parameters: {'n_estimators': 92, 'learning_rate': 0.2623438454218456, 'max_depth': 3, 'subsample': 0.9284572531960569, 'gamma': 4.588171137218182, 'reg_alpha': 3.1874594134299588, 'reg_lambda': 4.837139311678169}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:35,572] Trial 36 finished with value: 0.9060987415295256 and parameters: {'n_estimators': 90, 'learning_rate': 0.23717378617569193, 'max_depth': 7, 'subsample': 0.820165749162403, 'gamma': 4.021445540742366, 'reg_alpha': 2.0468065366729657, 'reg_lambda': 4.323957447540409}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:35,754] Trial 37 finished with value: 0.914811229428848 and parameters: {'n_estimators': 117, 'learning_rate': 0.2571352244063815, 'max_depth': 5, 'subsample': 0.7709349325236491, 'gamma': 4.806153755714089, 'reg_alpha': 3.481381905537047, 'reg_lambda': 4.259577242963006}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:35,976] Trial 38 finished with value: 0.925459825750242 and parameters: {'n_estimators': 162, 'learning_rate': 0.21338364707242785, 'max_depth': 4, 'subsample': 0.9181761509777017, 'gamma': 4.240161360107695, 'reg_alpha': 3.368866172893632, 'reg_lambda': 4.942030986939875}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:36,176] Trial 39 finished with value: 0.9177153920619555 and parameters: {'n_estimators': 130, 'learning_rate': 0.25377321603687986, 'max_depth': 5, 'subsample': 0.7725687194000425, 'gamma': 4.525123163324768, 'reg_alpha': 2.0267973972333344, 'reg_lambda': 4.749956069824434}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:36,352] Trial 40 finished with value: 0.9186834462729913 and parameters: {'n_estimators': 93, 'learning_rate': 0.24763903833053083, 'max_depth': 5, 'subsample': 0.8829373384052518, 'gamma': 4.598535900410625, 'reg_alpha': 2.1735255360117067, 'reg_lambda': 4.587620074319318}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:36,891] Trial 41 finished with value: 0.9177153920619555 and parameters: {'n_estimators': 197, 'learning_rate': 0.2165501470537687, 'max_depth': 6, 'subsample': 0.8894129244629231, 'gamma': 4.982248244550904, 'reg_alpha': 2.253818911668593, 'reg_lambda': 4.725775204129731}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:37,047] Trial 42 finished with value: 0.9225556631171346 and parameters: {'n_estimators': 76, 'learning_rate': 0.25303827068775864, 'max_depth': 3, 'subsample': 0.7258566374913027, 'gamma': 4.616802572381588, 'reg_alpha': 1.8304627117390981, 'reg_lambda': 4.61831490804607}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:37,230] Trial 43 finished with value: 0.9283639883833494 and parameters: {'n_estimators': 114, 'learning_rate': 0.20962841001204152, 'max_depth': 4, 'subsample': 0.8310862374105064, 'gamma': 4.9069944803451655, 'reg_alpha': 4.383865361167144, 'reg_lambda': 4.571831930338307}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:37,440] Trial 44 finished with value: 0.9235237173281704 and parameters: {'n_estimators': 98, 'learning_rate': 0.14766103482898246, 'max_depth': 4, 'subsample': 0.8535733413152831, 'gamma': 4.514881447677227, 'reg_alpha': 2.7462052642516595, 'reg_lambda': 4.8602503349153645}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:37,590] Trial 45 finished with value: 0.920619554695063 and parameters: {'n_estimators': 71, 'learning_rate': 0.19990230140948106, 'max_depth': 4, 'subsample': 0.7826935644563449, 'gamma': 4.876431536380671, 'reg_alpha': 3.164817114886612, 'reg_lambda': 4.446578033681866}. Best is trial 21 with value: 0.9332042594385286.
[I 2026-10-07 22:17:37,811] Trial 46 finished with value: 0.9341723136495643 and parameters: {'n_estimators': 154, 'learning_rate': 0.16764564088835285, 'max_depth': 3, 'subsample': 0.9064275991444303, 'gamma': 4.870436683214136, 'reg_alpha': 2.7544580335522997, 'reg_lambda': 4.437112298600285}. Best is trial 46 with value: 0.9341723136495643.
[I 2026-10-07 22:17:38,007] Trial 47 finished with value: 0.925459825750242 and parameters: {'n_estimators': 134, 'learning_rate': 0.23934497233770455, 'max_depth': 4, 'subsample': 0.919082037167297, 'gamma': 4.8574651213171665, 'reg_alpha': 1.8205128187561652, 'reg_lambda': 4.888033902771569}. Best is trial 46 with value: 0.9341723136495643.
[I 2026-10-07 22:17:38,208] Trial 48 finished with value: 0.9177153920619555 and parameters: {'n_estimators': 127, 'learning_rate': 0.21930666916024855, 'max_depth': 5, 'subsample': 0.7987345851463686, 'gamma': 4.950497362963507, 'reg_alpha': 2.2800791584315814, 'reg_lambda': 4.088253644023577}. Best is trial 46 with value: 0.9341723136495643.
[I 2026-10-07 22:17:38,364] Trial 49 finished with value: 0.9196515004840271 and parameters: {'n_estimators': 69, 'learning_rate': 0.2259960967215905, 'max_depth': 5, 'subsample': 0.900090237382227, 'gamma': 4.912854664378396, 'reg_alpha': 2.4956382230001295, 'reg_lambda': 4.446660369787057}. Best is trial 46 with value: 0.9341723136495643.

Best hyperparameters: {'n_estimators': 154, 'learning_rate': 0.16764564088835285, 'max_depth': 3, 'subsample': 0.9064275991444303, 'gamma': 4.870436683214136, 'reg_alpha': 2.7544580335522997, 'reg_lambda': 4.437112298600285}
Best recall score: 0.9341723136495643

In [46]:
best_params = study.best_params
best_model = XGBClassifier(**best_params)
best_model.fit(X_train_resampled, y_train_resampled)
best_proba = best_model.predict_proba(X_test_resampled)[:, 1]
best_y_pred = (best_proba >= THRESHOLD).astype(int)
print(f"Recall:    {recall_score(y_test_resampled, best_y_pred, zero_division=0):.2%}")
print(f"Precision: {precision_score(y_test_resampled, best_y_pred, zero_division=0):.2%}")
print(f"F1-score:  {f1_score(y_test_resampled, best_y_pred, zero_division=0):.2%}")
print(f"Accuracy:  {accuracy_score(y_test_resampled, best_y_pred):.2%}")

Recall:    93.42%
Precision: 73.05%
F1-score:  81.99%
Accuracy:  79.48%